autoInstallPeers: true

ignoredBuiltDependencies:
  - '@nestjs/core'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver

strictPeerDependencies: false
